info:
  name: List roles
  type: http
  seq: 1
  tags:
    - roles
    - crud

http:
  method: GET
  url: "{{baseUrl}}/roles"
  params:
    - name: page
      value: "{{page}}"
      type: query
    - name: pageSize
      value: "{{pageSize}}"
      type: query
  auth: inherit

runtime:
  assertions:
    - expression: res.status
      operator: eq
      value: "200"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
